version: '3.8'
services:
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.11.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    ports:
      - '4455:3000'
    networks:
      - intranet
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v0.11.0
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
    environment:
      - DSN=postgres://kratos:secret@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
  kratos:
    image: oryd/kratos:v0.11.0
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    depends_on:
      - kratos-migrate
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    environment:
      - DSN=postgres://kratos:secret@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    ports:
      - 5438:5432
    volumes: 
      - kratos_db:/var/lib/postgresql/data
    networks:
     - intranet
networks:
  intranet:
volumes:
  kratos_db:
    driver: local